# Generated by Django 6.0.6 on 2026-06-04 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_zone', models.CharField(choices=[('section', 'Section'), ('bloc', 'Bloc'), ('allee', 'Allée'), ('non_exploitable', 'Zone non exploitable')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
            },
        ),
        migrations.CreateModel(
            name='Caveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('longueur', models.FloatField(help_text='Longueur en mètres')),
                ('largeur', models.FloatField(help_text='Largeur en mètres')),
                ('etat', models.CharField(choices=[('disponible', 'Disponible'), ('reserve', 'Réservé'), ('occupe', 'Occupé'), ('non_exploitable', 'Non exploitable')], default='disponible', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caveaux', to='terrain.zone')),
            ],
            options={
                'verbose_name': 'Caveau',
                'verbose_name_plural': 'Caveaux',
            },
        ),
    ]
