# Generated by Django 6.0.6 on 2026-06-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='mode_paiement_prefere',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money'), ('airtel_money', 'Airtel Money'), ('especes', 'Especes'), ('virement', 'Virement')], default='especes', max_length=20),
        ),
    ]
