# Generated by Django 6.0.6 on 2026-06-04 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        ('terrain', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_concession', models.CharField(choices=[('temporaire', 'Temporaire'), ('perpetuelle', 'Perpétuelle')], max_length=20)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('expiree', 'Expirée'), ('resiliee', 'Résiliée')], default='active', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concessions', to='terrain.caveau')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concessions', to='users.user')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='concession', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Concession',
                'verbose_name_plural': 'Concessions',
            },
        ),
        migrations.CreateModel(
            name='Exhumation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('demandee', 'Demandée'), ('validee', 'Validée'), ('effectuee', 'Effectuée'), ('refusee', 'Refusée')], default='demandee', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('concession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhumations', to='concessions.concession')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhumations', to='users.user')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhumations_validees', to='users.user')),
            ],
            options={
                'verbose_name': 'Exhumation',
                'verbose_name_plural': 'Exhumations',
            },
        ),
    ]
