# Generated by Django 6.0.6 on 2026-06-04 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('payee', 'Payée'), ('partiellement_payee', 'Partiellement payée'), ('annulee', 'Annulée')], default='en_attente', max_length=25)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('date_echeance', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='users.user')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('airtel_money', 'Airtel Money'), ('especes', 'Espèces'), ('virement', 'Virement')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='finance.facture')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
    ]
